[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
name = "example"
version = "0.1.0"

[dependencies]
glib = "^0.1.3"
glib-sys = "^0.3.4"

[dependencies.webkit2gtk-webextension]
path = ".."
#git = "https://github.com/antoyo/webkit2gtk-webextension-rs"
version = "^0.1"

[dependencies.webkit2gtk-webextension-sys]
git = "https://github.com/antoyo/webkit2gtk-webextension-sys-rs"
version = "^0.2"

[features]
default = ["webkit2gtk-webextension/v2_2"]

[lib]
crate-type = ["dylib"]

[replace."glib:0.1.3"]
branch = "crate"
git = "https://github.com/antoyo/glib"
