[package]
name = "example"
version = "0.1.0"
authors = ["Antoni Boucher <bouanto@zoho.com>"]

[lib]
crate-type = ["dylib"]

[dependencies]

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"
version = "0.1.0"

[dependencies.webkit2webextension]
path = ".."

[dependencies.webkit2webextension-sys]
path = "../../webkit2webextension-sys"
