[package]
name = "webkit2webextension"
version = "0.1.0"
authors = ["Antoni Boucher <bouanto@zoho.com>"]

[dependencies]
glib = "^0.1"
gtk = "^0.1"

[dependencies.webkit2webextension-sys]
path = "../webkit2webextension-sys"
