[package]
name = "webkit2gtk-webextension"
version = "0.1.0"
authors = ["The Gtk-rs Project Developers"]

categories = ["api-bindings", "gui"]
description = "Rust bindings for the GTK+ 3 library"
repository = "https://github.com/gtk-rs/gtk"
license = "MIT"
homepage = "http://gtk-rs.org/"
documentation = "http://gtk-rs.org/docs/gtk/"

keywords = ["webkit", "gtk", "gtk-rs", "GUI"]

[badges]
travis-ci = { repository = "gtk-rs/webkit2gtk-webextension-rs" }

[lib]
name = "webkit2gtk_webextension"

[features]
v2_2 = []
v2_8 = ["v2_2", "webkit2gtk-webextension-sys/v2_8"]
v2_10 = ["v2_8", "webkit2gtk-webextension-sys/v2_10"]
v2_12 = ["v2_10", "webkit2gtk-webextension-sys/v2_12"]
v2_14 = ["v2_12", "webkit2gtk-webextension-sys/v2_14"]
v2_16 = ["v2_14", "webkit2gtk-webextension-sys/v2_16"]

[dependencies]
glib = { git = "https://github.com/gtk-rs/glib" }
glib-sys = { git = "https://github.com/gtk-rs/sys" }
gobject-sys = { git = "https://github.com/gtk-rs/sys" }
gtk = { git = "https://github.com/gtk-rs/gtk" }
libc = "^0.2"

[dependencies.webkit2gtk-webextension-sys]
git = "https://github.com/gtk-rs/webkit2gtk-webextension-rs"
version = "^0.2"
