[package]
name = "webkit2gtk-webextension-sys"
version = "0.3.1"
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"

categories = ["api-bindings", "gui"]
description = "Rust bindings for the webkit2gtk-webextension library"
repository = "https://github.com/gtk-rs/webkit2gtk-webextension-rs"
license = "MIT"
homepage = "http://gtk-rs.org/"
links = "webkit2gtk_webextension"

[lib]
name = "webkit2gtk_webextension_sys"

[features]
v2_6 = []
v2_8 = ["v2_6"]
v2_10 = ["v2_8"]
v2_12 = ["v2_10"]
v2_14 = ["v2_12"]
v2_16 = ["v2_14"]
v2_18 = ["v2_16"]

[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
bitflags = "0.9"
glib-sys = "^0.4.0"
gobject-sys = "^0.4.0"
gtk = "^0.2.0"
gtk-sys = "^0.4.0"
libc = "0.2"
javascriptcore-rs-sys = "^0.1"
soup-sys = "^0.4"
